#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
sudo ln -sf "$DIR/libgbm.so.1" "/usr/local/lib/aarch64-linux-gnu/libgbm.so.1"
sudo weston-launch --tty=/dev/tty1 --user=ark -- --use-pixman &